name: Override cargo dependency
description: |
  Override cargo dependency in project's root Cargo.toml manifest.

inputs:
  override:
    description: "Dependencies override"
    required: true

runs:
  using: composite

  steps:
    - name: Setup dasel
      uses: allejo/setup-dasel@v1

    - name: Print override
      shell: bash
      id: packages
      run: |
        # Print override
        echo '${{ inputs.override }}' | dasel -p toml -m '.[*].[*]' --colour
        # Prepare update command
        update=$(echo '${{ inputs.override }}' | dasel -p toml -m --format '{{ selectMultiple ".-" | format "-p {{ . }} " }}' '.[*].[*]')
        echo "::set-output name=update::${update}"

    - name: Set override
      shell: bash
      run: |
        # Set override
        echo "${version}" >> Cargo.toml

    - name: Update Cargo.lock
      shell: bash
      env:
        CARGO_UNSTABLE_SPARSE_REGISTRY: true
      run: cargo update ${{ steps.packages.outputs.update }}
