name: Set cargo dependencies version
description: |
  Sets cargo dependencies version in Cargo.toml

inputs:
  dependencies:
    description: "Map of dependencies to set in Cargo.toml"
    required: true

runs:
  using: composite

  steps:
    - name: Print dependencies
      shell: bash
      run: |
        # Print dependencies
        echo '${{ inputs.dependencies }}' | jq -C
        echo '${{ inputs.dependencies }}' | jq -c > input.json

    - name: Setup pytho
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install python dependencies
      shell: bash
      run: |
        # Install python dependencies
        python -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: Override dependencies
      shell: bash
      run: |
        # Override dependencies
        python ${{ github.action_path }}/cargo-set-dependency.py

    - name: Update Cargo.lock
      shell: bash
      env:
        CARGO_UNSTABLE_SPARSE_REGISTRY: true
      run: |
        # Update Cargo.lock
        packages=$(cat input.json | jq -rc '.[].package |= "-p " + . | .[].package')
        cargo update $packages

    - name: Setup dasel
      shell: bash
      uses: allejo/setup-dasel@v1

    - name: Print results to check summary
      shell: bash
      run: |
        cat <<TABLE >> $GITHUB_STEP_SUMMARY
        ## Used versions
        | name | version |
        | ---- | ------- |
        TABLE
        while read -r package; do
        cat <<VERSIONS >> $GITHUB_STEP_SUMMARY
        | ${package} | $(dasel -f Cargo.lock -p toml "package.(name=${package}).version -m")
        VERSIONS
