name: Set cargo dependencies version
description: |
  Sets cargo dependencies version in Cargo.toml

inputs:
  dependencies:
    description: "Map of dependencies to set in Cargo.toml"
    required: true

runs:
  using: composite

  steps:
    - name: Print dependencies
      shell: bash
      run: |
        # Print dependencies
        echo '${{ inputs.dependencies }}' | jq
        echo '${{ inputs.dependencies }}' | jq -c > input.json

    - name: Setup pytho
      uses: actions/setup-python@v4

    - name: Override dependencies
      shell: bash
      run: |
        # Override dependencies
        python cargo-set-dependencies.py

    - name: Update Cargo.lock
      shell: bash
      env:
        CARGO_UNSTABLE_SPARSE_REGISTRY: true
      run: cargo update --wrokspace
