name: Check connectivity to Fluence peer
description: |
  Check connectivity to Fluence peer or peers

inputs:
  target:
    description: "Fluence environment (stage, testnet or krasnodar) or peer multiaddr."
    default: "krasnodar"
  script:
    description: "Path to aqua script to run."
    default: "${{ github.action_path }}/heathcheck.aqua"
  function:
    description: "Function to run."
    default: "check_connection()"

outputs:
  log:
    description: "aqua script log"
    value: ${{ steps.check.outputs.log }}

runs:
  using: composite

  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install aqua
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Install aqua
        npm install --no-audit --no-fund --silent

    - name: Check env
      shell: bash
      run: env

    - name: Check connectivity to ${{ inputs.target }}
      id: check
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Check connectivity to ${{ inputs.target }}
        ./check.sh ${{ inputs.target }} ${{ inputs.script }} ${{ inputs.function }}
