name: Check connectivity to Fluence peer
description: |
  Check connectivity to Fluence peer or peers

inputs:
  target:
    description: "Fluence environment (stage, testnet or krasnodar) or peer multiaddr."
    default: "krasnodar"
  aqua-version:
    description: "aqua version to use"
    default: "latest"

outputs:
  log:
    description: "aqua script log"
    value: ${{ steps.check.outputs.log }}

runs:
  using: "node16"
  main: "dist/index.js"
