name: Check connectivity in fluence env
description: |
  Check connectivity in fluence env

inputs:
  env:
    description: "Fluence environment (stage, testnet or krasnodar)"
    required: true
  timeout:
    description: "Timeout in milliseconds"
    required: false
    default: "25000"
outputs:
  error_log:
    description: "Error messages from checkPeer"

runs:
  using: "node16"
  main: "src/index.js"
