name: Check connectivity in fluence env
description: |
  Check connectivity in fluence env

inputs:
  env:
    description: "Fluence environment (stage, testnet or krasnodar)"
    required: true
  timeout:
    description: "Timeout in milliseconds"
    required: false
    default: "10000"
outputs:
  error_log:
    description: "Error messages from checkPeer"
    value: ${{ steps.check.outputs.error_log }}

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        registry-url: "https://registry.npmjs.org"

    - run: pnpm i
      working-directory: ${{ github.action_path }}
      shell: bash

    - run: pnpm run build
      working-directory: ${{ github.action_path }}
      shell: bash

    - run: pnpm run action --silent
      id: check
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        INPUT_ENV: ${{ inputs.env }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
