name: Check connectivity in fluence env
description: |
  Check connectivity in fluence env

inputs:
  env:
    description: "Fluence environment (stage, testnet or krasnodar)"
    required: true
  timeout:
    description: "Timeout in milliseconds"
    required: false
    default: "10000"
outputs:
  error_log:
    description: "Error messages from checkPeer"

runs:
  using: "composite"
  env:
    CI: true
    FORCE_COLOR: true
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
        cache-dependency-path: ${{ github.action_path }}/package-lock.json
        cache: "npm"

    - run: npm i
      working-directory: ${{ github.action_path }}
      shell: bash

    - run: npm run action --silent
      working-directory: ${{ github.action_path }}
      shell: bash
