name: Override dependencies in pnpm project
description: |
  Override dependencies in pnpm project

inputs:
  dependencies:
    description: "JSON of dependencies"
    type: string
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
