name: Publish npm snapshot
description: |
  Publish npm packages snapshot to fluence registry

inputs:
  working-directory:
    description: "Directory where to run the commands"
    type: string
    default: "${{ github.workspace }}"
  id:
    description: "Snapshot id"
    type: string
    required: true

outputs:
  version:
    description: "Version of published snapshot"
    value: "${{ steps.version.outputs.version }}"

runs:
  using: composite
  steps:
    - name: Check inputs
      shell: bash
      run: |
        if [[ "${{ inputs.id }}" == "" ]]; then
          echo "id input is empty"
          exit 1
        fi

    # - name: Run npm install
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    #   run: npm install

    # - name: Run npm build
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    #   run: npm run build

    - name: Set package version
      id: version
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        # Set package vesion
        echo "version=$(npm version prerelease --no-git-tag-version --preid ${{ inputs.id }})" >> $GITHUB_OUTPUT
        cat package.json

    # - name: Publish to self-hosted npm repo
    #   working-directory: ${{ inputs.working-directory }}
    #   run: npm publish --tag snapshot --registry https://npm.fluence.dev
