/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.12.3
 *
 */

import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client';
    


// Services
export interface OpStringDef {
    concat_strings: (a: string, b: string, c: string, d: string, e: string, f: string, callParams: CallParams$$<'a' | 'b' | 'c' | 'd' | 'e' | 'f'>) => string | Promise<string>;
    identity: (s: string, callParams: CallParams$$<'s'>) => string | Promise<string>;
}
export function registerOpString(service: OpStringDef): void;
export function registerOpString(serviceId: string, service: OpStringDef): void;
export function registerOpString(peer: IFluenceClient$$, service: OpStringDef): void;
export function registerOpString(peer: IFluenceClient$$, serviceId: string, service: OpStringDef): void;
       

// Functions
 

export function checkPeer(
    targetPeer: string,
    validatorPeer: string,
    timeout: number,
    config?: {ttl?: number}
): Promise<string[]>;

export function checkPeer(
    peer: IFluenceClient$$,
    targetPeer: string,
    validatorPeer: string,
    timeout: number,
    config?: {ttl?: number}
): Promise<string[]>;


/* eslint-enable */