/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.9.1-374
 *
 */
import { FluencePeer } from '@fluencelabs/fluence';

import {
    callFunction$$,
    registerService$$,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v4.js';


// Services
export interface OpStringDef {
    concat_strings: (a: string, b: string, c: string, d: string, e: string, f: string, callParams: CallParams$$<'a' | 'b' | 'c' | 'd' | 'e' | 'f'>) => string | Promise<string>;
    identity: (s: string, callParams: CallParams$$<'s'>) => string | Promise<string>;
}
export function registerOpString(service: OpStringDef): void;
export function registerOpString(serviceId: string, service: OpStringDef): void;
export function registerOpString(peer: FluencePeer, service: OpStringDef): void;
export function registerOpString(peer: FluencePeer, serviceId: string, service: OpStringDef): void;
       

// Functions
 

export function checkPeer(
    targetPeer: string,
    validatorPeers: string[],
    timeout: number,
    config?: {ttl?: number}
): Promise<string[]>;

export function checkPeer(
    peer: FluencePeer,
    targetPeer: string,
    validatorPeers: string[],
    timeout: number,
    config?: {ttl?: number}
): Promise<string[]>;


/* eslint-enable */