name: Set dependency version in node project
description: |
  Sets dependency version in node project

inputs:
  package:
    description: "Package name"
    type: string
    required: true
  version:
    description: "Package version"
    type: string
    required: true
  working-directory:
    description: "Working directory"
    type: string
    default: "${{ github.workspace }}"

runs:
  using: composite

  steps:
    - name: Override dependency
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      run: npm install -E ${{ inputs.package }}@${{ inputs.version }}
