name: Set dependency version in node project
description: |
  Sets dependency version in node project

inputs:
  package:
    description: "Package name"
    type: string
    required: true
  version:
    description: "Package version"
    type: string
    required: true
  working-directory:
    description: "Working directory"
    type: string
    default: "${{ github.workspace }}"
  package-manager:
    description: "Package manager to use"
    type: string
    default: "npm"
  flags:
    description: "Flags to pass to npm"
    type: string
    default: "--save"

runs:
  using: composite

  steps:
    - name: Override dependency
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      run: ${{ inputs.package-manager }} install ${{ inputs.flags }} -E ${{ inputs.package }}@${{ inputs.version }}
