name: Test cargo-set-dependency

on:
  pull_request:
    paths:
      - "cargo-set-dependency/**"
      - ".github/workflows/cargo-set-dependency-ci.yml"
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  cargo-set-dependency:
    name: "Set version"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Prepare Cargo.toml
        run: |
          cat <<-CARGO > Cargo.toml
          [package]
          name = "test"
          version = "0.1.0"
          edition = "2018"

          [dependencies]
          fluence-app-service = "0.20.0"
          marine-runtime = "0.20.0"
          CARGO

      - name: Prepare cargo source
        run: |
          mkdir src
          cat <<-SRC > src/main.rs
          fn main() {
              println!("Hello, world!");
          }
          SRC

      - name: Set cargo version
        uses: ./cargo-set-dependency
        with:
          dependencies: |
            [
              {
                "package": "fluence-app-service",
                "version": "=0.22.2",
                "features": ["raw-module-api"]
              }
            ]
