name: Test fluence-healthcheck

on:
  pull_request:
    paths:
      - "fluence-healthcheck/**"
      - ".github/workflows/fluence-healthcheck.yml"
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  healthcheck:
    name: "connectivity - stage"
    runs-on: ubuntu-latest

    steps:
      - name: Run check
        with:
          env: stage

      - uses: jenseng/dynamic-uses@v1
        with:
          uses: fluencelabs/github-actions/fluence-healthcheck@${{ github.ref }}
          with: '{ "env": "stage" }'
